networks:
  transcendence-net:
    driver: bridge

services:
  app:
    build:
      context: .
    image: transcendence:latest
    container_name: transcendence
    # NO PORT MAPPING please DONT change this
    # app shall be accessible ONLY through our WAF proxy
    env_file:
      - .env
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
      DB: "/data/transcendence.db"
    volumes:
      - ./data:/data
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - transcendence-net

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: transcendence-waf
    depends_on:
      - app
    environment:
      BACKEND: "http://app:3000"
      PORT: "8080"
      SSL_PORT: "8443"
      SERVER_NAME: "transcendence.nip.io"
      NGINX_ALWAYS_TLS_REDIRECT: "on"
      MODSEC_RULE_ENGINE: "off"
      DETECTION_PARANOIA: "2"
      BLOCKING_PARANOIA: "2"
      ANOMALY_INBOUND: "6"
      ANOMALY_OUTBOUND: "4"
    ports:
      - "3000:8443"
    volumes:
      - ./waf/nginx/templates/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./waf/modsec/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:/etc/modsecurity.d/owasp-crs/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf:ro
    restart: unless-stopped
    networks:
      - transcendence-net

