networks:
  transcendence-net:
    driver: bridge

services:
  app:
    build:
      context: .
    image: transcendence:latest
    container_name: transcendence
    # NO PORT MAPPING please DONT change this
    # app shall be accessible ONLY through our WAF proxy
    env_file:
      - .env
    environment:
      PORT: "3000"
      HOST: "0.0.0.0"
      DB: "/data/transcendence.db"
    volumes:
      - ./data:/data
    expose:
      - "3000"
    restart: unless-stopped
    networks:
      - transcendence-net

  waf:
    image: owasp/modsecurity-crs:nginx
    container_name: transcendence-waf
    depends_on:
      - app
    environment:
      # WAF <-> app comms 
      # (They talk thru HTTP)
      BACKEND: "http://app:3000"

      # WAF listening ports
      PORT: "8080"
      SSL_PORT: "8443"
      SERVER_NAME: "transcendence.nip.io" # domain "transcendence.nip.io"
      NGINX_ALWAYS_TLS_REDIRECT: "on"

      # CORE SETUP
      MODSEC_RULE_ENGINE: "On" # if u want 2 do some log validation / testing, set "DetectionOnly"
      DETECTION_PARANOIA: "2"
      BLOCKING_PARANOIA: "2"
      ANOMALY_INBOUND: "4"
      ANOMALY_OUTBOUND: "4"

    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - ./waf/nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    restart: unless-stopped
    networks:
      - transcendence-net
